### ISSUE TITLE
Symflower: Connection to the language server is not active

### ISSUE THREAD

**Issue by MOHAND99** [symflower/symflower#34] opened 2024-07-20 05:54 UTC
I got this error message `Symflower: Connection to the language server is not active.`
I was running `Symflower: Generate Test Template for Function` on an endpoint in a MVC controller.

Windows 10 Enterprise
VS Code  1.91.1, Intellij 2023.1.2

**Comment by imamkriswanto11** [comment] 2024-08-06 04:14
Hi, is this issue has been solved ?
just tried symflower for my spring boot project using vscode but can't generate unit test code because of this issue.

**Comment by zimmski** [comment] 2024-08-29 17:59
I think that this issue is a duplicate of #36 which we solved with version 39798. There have been different errors depending on which version (if at all) you had previously installed.

@MOHAND99 @imamkriswanto11 @grihenrik please let me know if Symflower now works. Great start would be our Java tutorial https://symflower.com/en/products/symflower-cli/tutorial/vscode-java/ which should give you a good overview on common Symflower features. Let me know how it went. I am also always up for a video session to see cases we do not support yet.

**Closed by zimmski** 2024-08-29 17:59 UTC
Labels: bug
