### ISSUE TITLE
Unit test generation for Java are not supported with this version

### ISSUE THREAD

**Issue by bobbyb67** [symflower/symflower#14] opened 2022-08-18 19:27 UTC
When executing unit test generation from within intelliJ, I receive the following message:

Unit test generation for Java are not supported with this version

**Comment by bauersimon** [comment] 2022-08-22 08:37
Can you please provide your IntelliJ, Symflower and Java versions?

**Comment by zimmski** [comment] 2022-08-22 10:08
This is indeed strange @bobbyb67 could you upload the log of the extension as well please. (Due to its size attached as a file would be good.) You can open the log with the icon on the bottom:

![Screenshot_20220822_120731](https://user-images.githubusercontent.com/1847950/185896469-ae940481-7568-47bf-8d65-65c0e88bcdbc.png)

**Comment by zimmski** [comment] 2022-09-21 10:05
@bobbyb67 Will close this issue, since we cannot reproduce the problem. The message you are seeing is thrown in our source code either when we do not support an action at all for a language, but that is impossible for Java, and the other reason is the usage of a JAR file as dependency. We do not have a test case for that yet, so if that is the case. Please let us know, we have not yet seen this and would be eager to see an example to better understand why this is used and how we can support it.

**Closed by zimmski** 2022-09-21 10:05 UTC
