### ISSUE TITLE
Symflower throwing an exception on IDE restart/switching to a different project

### ISSUE THREAD

**Issue by Xanaxiel** [symflower/symflower#31] opened 2023-04-28 22:10 UTC
Hello just reporting a minor issue (already kinda bugged nerves everytime I switch workspaces)

When switching workspaces or opening another project an exception occurs (probably because Symflower language server is already running in the background). Not sure if it's IntelliJ plugin behavior that needs to hook on startup, or maybe something funky occured.

![image](https://user-images.githubusercontent.com/19189593/235261637-87cc1bd4-a8ae-4b63-ac38-30393a677a1c.png)

```
java.lang.RuntimeException: java.lang.Exception: Language server already running.
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:37)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:269)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:268)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:268)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.Exception: Language server already running.
	at com.symflower.languageserver.LSWrapper.startServer(LSWrapper.java:68)
	at com.symflower.activity.ExtensionStartupActivity.runActivity(ExtensionStartupActivity.java:35)
	... 17 more
```

**Comment by zimmski** [comment] 2023-05-02 08:24
Thanks for the bug report @Xanaxiel. I have seen this in the last days during a user interview that had 2023.1 installed. Which version do you have installed?

**Comment by bauersimon** [comment] 2023-05-03 07:44
@Xanaxiel could you please help me out with some more details on this? In particular:

- which `IntelliJ` version are you using?
- which OS are you on?

I couldn't reproduce this on version `2022.2` on my Linux machine, yet. Thanks for the help!

**Comment by Xanaxiel** [comment] 2023-05-03 16:03
IntelliJ Version IntelliJ IDEA 2023.1.1 (Ultimate Edition)
Build #IU-231.8770.65

OS 
Windows 10 Pro Version	22H2


`symflower version` output:

```
symflower v26016 on windows/amd64

BuildVersion: 19045.2846
Path: ..paths omitted..
ProductName: Windows 10 Pro
ProductVersion: 6.3
ProductVersionMajor: 10
ProductVersionMinor: 0
```

**Comment by Xanaxiel** [comment] 2023-05-03 16:04
Apologies misclicked the _close with comment_ button

**Comment by zimmski** [comment] 2023-05-22 10:00
@Xanaxiel this should be fixed beginning with version 29826. Sorry for taking so long, we had to fix a bunch of smaller problems around this one and added some new testing infrastructure to allow for multiple-window-intellij-tests. Kind of crazy how much went in, just to make sure that we can then check that our process locking is working during the installation of the extension. Anyway! Thanks so much for using Symflower, let us know if there is anything else that bugs you or you want to see. We are currently working down our test-template bug/feature list so you should see improvements there every day.

**Closed by zimmski** 2023-05-22 10:00 UTC
Labels: bug
